version: '3'

services:
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis

  redis:
    image: "redis/redis-stack"
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - .data:/data
